version: "3.8"

services:
  mongo:
    image: mongo:6.0 # hoặc bản mới nhất
    container_name: my-mongo
    ports:
      - "27017:27017" # Mở cổng MongoDB mặc định
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db # Dữ liệu sẽ được lưu lại sau khi stop container

volumes:
  mongo-data:
